on: push

name: Handle Commit
jobs:
  generate:
    name: handle commit
    runs-on: ubuntu-latest
    container: clojure:openjdk-8-lein-2.9.8-buster
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Run test
        run: |
          lein test

      - name: Generate the artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          lein bin


      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: reverso-0.1.0
          path: target/reverso-0.1.0-SNAPSHOT

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: reverso-0.1.0
